from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
import json

from project_platform.core import GraphPlatform


def index(request):
    """Main page"""
    return render(request, 'index.html', {'message': 'Radi. Ovo je samo test prikaz.'})


def graph_data(request):
    """
    Returns the current graph from the platform as JSON.
    """
    platform = GraphPlatform()
    graph = platform.current_graph

    if graph is None:
        return JsonResponse({'nodes': {}, 'edges': [], 'directed': True})

    data = {
        'directed': graph.directed,
        'nodes': {
            node_id: {
                'id': node.id,
                'attributes': node.attributes,
            }
            for node_id, node in graph.nodes.items()
        },
        'edges': [
            {
                'id': edge.id,
                'source': edge.source,
                'target': edge.target,
                'attributes': edge.attributes,
            }
            for edge in graph.edges.values()
        ],
    }

    return JsonResponse(data)


def list_plugins(request):
    # getting all plugin names from the GraphPlatform
    plugins = GraphPlatform().get_data_source_plugins()
    # safe=False allows us to return a list instead of a dict
    return JsonResponse(plugins, safe=False)


def get_data_plugin_parameters(request, plugin_name):
    """
    API endpoint koji vraća parametre za dati plugin.
    GET /api/plugins/<plugin_name>/parameters/
    """
    platform = GraphPlatform()
    try:
        parameters = platform.get_data_source_plugin_parameters(plugin_name)
        return JsonResponse(parameters, safe=False)
    except ValueError as e:
        return JsonResponse({'error': str(e)}, status=404)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["POST"])
def load_graph(request):
    try:
        data = json.loads(request.body)

        data_source = data.get('plugin')
        visualizer = data.get('visualizer', 'simple-view')
        parameters = data.get('parameters', {})

        platform = GraphPlatform()

        graph = platform.load_graph(
            data_source_plugin_name=data_source,
            visualizer_plugin_name=visualizer,
            **parameters
        )

        node_count = len(graph.nodes) if graph and hasattr(
            graph, 'nodes') else 0
        edge_count = len(graph.edges) if graph and hasattr(
            graph, 'edges') else 0

        return JsonResponse({
            'status': 'success',
            'message': f'Graph loaded with {data_source}',
            'visualizer': visualizer,
            'node_count': node_count,
            'edge_count': edge_count
        })

    except Exception as e:
        import traceback
        traceback.print_exc()
        return JsonResponse({'error': str(e)}, status=500)


def list_visualizers(request):
    platform = GraphPlatform()
    visualizers = platform.get_visualizer_plugins()
    return JsonResponse(visualizers, safe=False)


def render_graph(request):
    """
    Renders the current graph using the current visualizer plugin.
    Returns the HTML generated by the visualizer.
    """
    platform = GraphPlatform()

    try:
        html = platform.render_current_graph()
        response = HttpResponse(html)
        response['X-Frame-Options'] = 'SAMEORIGIN'
        return response
    except Exception as e:
        import traceback
        traceback.print_exc()
        return HttpResponse(f'<html><body><h1>Error rendering graph</h1><pre>{str(e)}</pre></body></html>', status=500)
